### ISSUE TITLE
Obtain support for Deploy the CAP Application Using SAP Business Application Studio

### ISSUE THREAD

**Issue by TobiasLudwig02** [SAP-samples/datasphere-build-apps-data-entry#4]
Hello,

I the steps of your post  and now I am trying to deploy the cap application, but I get some errors during the creation of the HDI container.

I changed all the relevant variables and names as you mentaioned in the create cap app section, added the credentials of the tech user in the usp file, but I still get the errors and the deployment of the CAPProxy-db-deployer app stops. 
Here are the relevant logs of the errors:

#2.0#2023 10 24 13:48:06.272#Z#DEBUG#com.sap.cloud.lm.sl.xs2.953a860f-7273-11ee-89ef-eeee0a8df860.ProjectdataCAPProxy-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-95168###
[PollExecuteTaskStatusExecution] [ProjectdataCAPProxy-db-deployer] 834e19bc-dba2-45a2-a428-50bb04599ea2 [2023-10-24T13:48:05.681310] Error: The file requires "db://DWCMISSION_CORP_CIT_PROJECTS_PROJECTDATA" which is not provided by any file [8212001] (STDERR, APP/TASK/deploy)#

#2.0#2023 10 24 13:48:06.272#Z#DEBUG#com.sap.cloud.lm.sl.xs2.953a860f-7273-11ee-89ef-eeee0a8df860.ProjectdataCAPProxy-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-95168###
[PollExecuteTaskStatusExecution] [ProjectdataCAPProxy-db-deployer] 834e19bc-dba2-45a2-a428-50bb04599ea2 [2023-10-24T13:48:05.681326] Error: Could not compose a consistent make graph [8212012] (STDERR, APP/TASK/deploy)#

#2.0#2023 10 24 13:48:06.272#Z#DEBUG#com.sap.cloud.lm.sl.xs2.953a860f-7273-11ee-89ef-eeee0a8df860.ProjectdataCAPProxy-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-95168###
[PollExecuteTaskStatusExecution] [ProjectdataCAPProxy-db-deployer] 834e19bc-dba2-45a2-a428-50bb04599ea2 [2023-10-24T13:48:05.681328] Error: Calculating dependencies... failed [8212108] (STDERR, APP/TASK/deploy)#

#2.0#2023 10 24 13:48:06.272#Z#DEBUG#com.sap.cloud.lm.sl.xs2.953a860f-7273-11ee-89ef-eeee0a8df860.ProjectdataCAPProxy-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-95168###
[PollExecuteTaskStatusExecution] [ProjectdataCAPProxy-db-deployer] 834e19bc-dba2-45a2-a428-50bb04599ea2 [2023-10-24T13:48:05.681330] Error: Making... failed [8211605] (STDERR, APP/TASK/deploy)#

#2.0#2023 10 24 13:48:06.272#Z#DEBUG#com.sap.cloud.lm.sl.xs2.953a860f-7273-11ee-89ef-eeee0a8df860.ProjectdataCAPProxy-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-95168###
[PollExecuteTaskStatusExecution] [ProjectdataCAPProxy-db-deployer] 834e19bc-dba2-45a2-a428-50bb04599ea2 [2023-10-24T13:48:05.681334] at "src/gen/ProjectdataService.Projectdata.hdbview" (13:6-46) (STDOUT, APP/TASK/deploy)#

#2.0#2023 10 24 13:48:06.272#Z#DEBUG#com.sap.cloud.lm.sl.xs2.953a860f-7273-11ee-89ef-eeee0a8df860.ProjectdataCAPProxy-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-95168###
[PollExecuteTaskStatusExecution] [ProjectdataCAPProxy-db-deployer] 834e19bc-dba2-45a2-a428-50bb04599ea2 [2023-10-24T13:48:05.681336] Error: Starting make in the container "DWC_HDI" with 9 files to deploy, 0 files to undeploy... failed [8214168] (STDERR, APP/TASK/deploy)#

#2.0#2023 10 24 13:48:06.272#Z#DEBUG#com.sap.cloud.lm.sl.xs2.953a860f-7273-11ee-89ef-eeee0a8df860.ProjectdataCAPProxy-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-95168###
[PollExecuteTaskStatusExecution] [ProjectdataCAPProxy-db-deployer] 834e19bc-dba2-45a2-a428-50bb04599ea2 [2023-10-24T13:48:05.681337] Make failed (4 errors, 3 warnings): tried to deploy 9 files, undeploy 0 files, redeploy 0 dependent files (STDOUT, APP/TASK/deploy)#

#2.0#2023 10 24 13:48:06.272#Z#DEBUG#com.sap.cloud.lm.sl.xs2.953a860f-7273-11ee-89ef-eeee0a8df860.ProjectdataCAPProxy-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-95168###
[PollExecuteTaskStatusExecution] [ProjectdataCAPProxy-db-deployer] 834e19bc-dba2-45a2-a428-50bb04599ea2 [2023-10-24T13:48:05.681828] Deployment to container DWC_HDI failed - error: HDI make failed [Deployment ID: none]. (STDERR, APP/TASK/deploy)#

#2.0#2023 10 24 13:48:06.272#Z#DEBUG#com.sap.cloud.lm.sl.xs2.953a860f-7273-11ee-89ef-eeee0a8df860.ProjectdataCAPProxy-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-95168###
[PollExecuteTaskStatusExecution] [ProjectdataCAPProxy-db-deployer] 834e19bc-dba2-45a2-a428-50bb04599ea2 [2023-10-24T13:48:05.682589] Deployment ended at 2023-10-24 13:48:05 (STDOUT, APP/TASK/deploy)#

#2.0#2023 10 24 13:48:06.272#Z#DEBUG#com.sap.cloud.lm.sl.xs2.953a860f-7273-11ee-89ef-eeee0a8df860.ProjectdataCAPProxy-db-deployer.executeTaskTask#
######org.cloudfoundry.multiapps.controller.persistence.services.ProcessLogger########flowable-async-job-executor-thread-95168###
[PollExecuteTaskStatusExecution] [ProjectdataCAPProxy-db-deployer] 834e19bc-dba2-45a2-a428-50bb04599ea2 [2023-10-24T13:48:05.682604] Error: HDI make failed (STDERR, APP/TASK/deploy)#

I can see the HDI container in Datasphere but get some erorrs when I try to add it like it the create analytic model section mentioned.

I am also confused, because I can't see the HDI container in the database explorer.

I hope you understand my problem and are able to help me.

Thank you very much in advance.

Tobias

**Comment by kpadmapriya** [comment]
Hi Tobias,

As per the log details you provided ( **Error: The file requires "db://DWCMISSION_CORP_CIT_PROJECTS_PROJECTDATA" which is not provided by any file**), I understand that you are providing sample data under data folder (db/data/...). Can you check this file name & content with your entity definition?

What error do you get in the Datasphere side when you try to add the HDI container into the space?

Regards,
Padmapriya

**Comment by TobiasLudwig02** [comment]
Hello Padmapriya,

yes, I am providing that file, but there was also a csv file in your sample data. Here you see the file and the data model:

![image](https://github.com/SAP-samples/datasphere-build-apps-data-entry/assets/91959779/84631256-c660-4121-b7bf-bd49c3d5850e)

The csv file has the name, which is mentioned in the error, but this one is not in the "gen" folder. I am not that familiar with building an mta project but I guess it deployes everything out of the gen folder? This is how it looks like: 

![image](https://github.com/SAP-samples/datasphere-build-apps-data-entry/assets/91959779/a7d9a578-dd1c-48c9-bc34-89c44b866185)

You can see there s no csv file under the folder db, should I add this there?


There error in Datasphere looks like this:

"The deployment of CORP_CIT_PROJECTS was unsuccessful. Failed to execute a database statement for Artifact #HDI_CONTAINERS_CORP_CIT_PROJECTS_ae4df2b2-5853-415e-bffb-06b53ef1b573 of type user-defined error: "DWC_TENANT_OWNER"."UPDATE_HDI_CONTAINERS_SPACE": line 130 col 7 (at pos 5477): "DWC_HDI"."DWC_CONSUMPTION_ROLE", "DWC_HDI"."DWC_CONSUMPTION_ROLE#": {2} Correlation ID: 5797d911-4c21-4917-43ea-20286fbefb7a"

 CORP_CIT_PROJECTS is the name of the sapce in Datasphere.

Thanks and kind regards,
Tobias

**Comment by kpadmapriya** [comment]
Hi Tobias,

Yes, the build should have the sample data under gen automatically. The exisitng file name does not match the error message and it is not taken for build process as well. I would suggest to rename the sample data file into the format **namespace-entity** (**dwcmission.corp_cit_projects-Projectdata**) or as expected in the error message.

Regards,
Padmapriya

**Comment by TobiasLudwig02** [comment]
Hi Padmapriya,

I tried it with both names but I get the same error. There is also no file in the gen folder.

Regards,
Tobias

**Comment by kpadmapriya** [comment]
Hi Tobias,

The CAP service in the tutorial has two entities, one with the annotation **@cds.persistence.exists**, so you create a view to **read data from Datasphere space** using User Provided Service & Datasphere Technical user without any sample data file for it. 

Second entity is without the annotation **cds.persistence.exists**, so it will be deployed using HDI container and can be **accessed from Datasphere** space and sample data file is provided for it.

In your application, only one entity and it is with the annotation **@cds.persistence.exists** and also providing sample data for it. 

If you are trying to reuse the second entity from the tutorial, then I would suggest to remove the annotation **@cds.persistence.exists**.  

Regards
Padmapriya

**Comment by kpadmapriya** [comment]
For further CAP knowledge, you may refer the below

- https://developers.sap.com/group.cap-application-full-stack.html
- https://developers.sap.com/group.deploy-full-stack-cap-application.html

**Comment by TobiasLudwig02** [comment]
Hi Padmapriya,

thanks for the hint! Now its deployed succesfully.

Just so I understand it right:
Without the @cds.persistence.exists  I am also able to wirte data into the dataset via Build Apps?
And with it I can just read the data with the cap service?

Thank you very much!

Tobias

**Comment by kpadmapriya** [comment]
Hi Tobias,

Glad that it helped.

Answer to your questions:

- Without the @cds.persistence.exists I am also able to wirte data into the dataset via Build Apps?
Yes, you can write into the dataset via Build Apps without this annotation.

- And with it I can just read the data with the cap service?
Once deployed, you can write new data and consume the exsiting data via CAP service endpoint

Regards
Padmapriya
