### ISSUE TITLE
Obtain support for Create a Destination in SAP BTP Cockpit

### ISSUE THREAD

**Issue by TobiasLudwig02** [SAP-samples/datasphere-build-apps-data-entry#5]
Hello,

when I set up the destination as described in the repo I get the error 401: Unauthorized.

This is how I have set it up:

![image](https://github.com/SAP-samples/datasphere-build-apps-data-entry/assets/91959779/d11aff03-3165-4327-b5b4-367e8953986f)

Also when I click on the endpoint I get different variables after the /:

![image](https://github.com/SAP-samples/datasphere-build-apps-data-entry/assets/91959779/a322eccb-adbe-4d2a-83ff-bf604fbd401a)

I just changed the name from tanks to project data, but I don't know why there is this /odata/v4/. This his how my cap-service file looks like:

![image](https://github.com/SAP-samples/datasphere-build-apps-data-entry/assets/91959779/dc9428e6-c755-4dbc-b296-7de9d40cfcc6)

Also the FieldTechnican Role Collection has no roles in it:

![image](https://github.com/SAP-samples/datasphere-build-apps-data-entry/assets/91959779/9a024f8a-f215-4746-ac28-9bdc2a964596)

Can you provide any solution on this topic?

Thanks and kind regards,

Tobias

**Comment by kpadmapriya** [comment]
Hi Tobias,

You have not added the role into the service endpoint. Try adding as TankVolume endpoint.

Best Regards
Padmapriya

**Comment by TobiasLudwig02** [comment]
Hi Padmapriya,

can you explain this in more detail? I dont use the sample data set so this is why I dont have the TankVolume dataset.

Best Regards

Tobias

**Comment by kpadmapriya** [comment]
Hi Tobias,

My suggestion was to specify the role for the service endpoint in the cap-service.cds file.

entity XXXX  @(restrict : [
            {
                grant : [ '*' ],
                to : [ 'FieldTechnician' ]
            }
             ]) as projection on db.XXXX;

Best Regards
Padmapriya

**Comment by TobiasLudwig02** [comment]
Hi Padmapriya,

it occures again the same error.

This is how the cap-service.cds file looks like:
![image](https://github.com/SAP-samples/datasphere-build-apps-data-entry/assets/91959779/147db7a0-cc90-449f-b7d6-58b83eecdc93)

And this is the data-models.cds:
![image](https://github.com/SAP-samples/datasphere-build-apps-data-entry/assets/91959779/6f1436f7-6a7a-428d-afe1-2fef65426f4d)

I am again confused why there is this /odata/v4/ in the URL:

![image](https://github.com/SAP-samples/datasphere-build-apps-data-entry/assets/91959779/11265fe9-5145-492f-92fe-511255374ff3)

I also noticed that the db-deplyer app says started in the overview but when I take a look at the details it says crashed with error 137. I found out that this error occures when there isnt enough memory so I increased the instance memory and disk but it crashed again: 

![image](https://github.com/SAP-samples/datasphere-build-apps-data-entry/assets/91959779/a3894287-e229-4722-8386-453fc27182e8)

Maybe there is a connection between those errors?

Best regards,

Tobias

**Comment by kpadmapriya** [comment]
Hi Tobias,

Do you see any detailed logs under your BTP suaccount for db-deployer?

1. choose your **BTP Subaccount >> your BTP Space >> XXXX-db-deployer**
2. Choose **Logs** from the left panel

Best Regards
Padmapriya

**Comment by TobiasLudwig02** [comment]
Hi Padmapriya,

these are the last logs:

2023-11-07T13:18:23.721+0000 [CELL/0] STDOUT Cell cd886fff-f3d6-4cad-8cc4-80893bd2b5a5 stopping instance ebd26d9c-6afa-46bd-5d05-c7c2
2023-11-07T13:18:23.721+0000 [CELL/0] STDOUT Cell cd886fff-f3d6-4cad-8cc4-80893bd2b5a5 destroying container for instance ebd26d9c-6afa-46bd-5d05-c7c2
2023-11-07T13:18:23.738+0000 [API/9] STDOUT Process has crashed with type: "web"
2023-11-07T13:18:23.751+0000 [API/9] STDOUT App instance exited with guid 834e19bc-dba2-45a2-a428-50bb04599ea2 payload: {"instance"=>"ebd26d9c-6afa-46bd-5d05-c7c2", "index"=>0, "cell_id"=>"cd886fff-f3d6-4cad-8cc4-80893bd2b5a5", "reason"=>"CRASHED", "exit_description"=>"Codependent step exited", "crash_count"=>15, "crash_timestamp"=>1699363103718769401, "version"=>"c3031cc0-d605-4caf-8943-6d8c5796309d"}
2023-11-07T13:18:23.926+0000 [PROXY/0] STDOUT Exit status 137
2023-11-07T13:18:25.479+0000 [CELL/0] STDOUT Cell cd886fff-f3d6-4cad-8cc4-80893bd2b5a5 successfully destroyed container for instance ebd26d9c-6afa-46bd-5d05-c7c2

Like I said before it crashed with the error 137.

Best Regards,

Tobias

**Comment by kpadmapriya** [comment]
Hi Tobias,

For destination issue, I would suggest you to try the below 

1. open `package.json` file in the CAP application and replace the below

```
"[production]": {
        "auth": {
          "kind": "xsuaa"
```

3.  with

```
"auth": {
        "kind": "basic",
        "users": {
          "field.technician@tester.sap.com": {
            "password": "initial",
            "roles": [
              "FieldTechnician"
            ]
          }
```

4. When you create the destination , add `/odata/v4/farm-tank`  to the url

Best Regards
Padmapriya

**Comment by TobiasLudwig02** [comment]
Hi Padmapriya,

this worked! Thanks a lot!

The db-deployer still crashes. Do you have any ideas?

Best Regards

Tobias

**Comment by kpadmapriya** [comment]
Hi Tobias,

The CAP application has `manifest.yml` with the memory details specified, so this application may not be the reason for the memory consumption issue. 

One suggestion would be, check the tips [here](https://me.sap.com/notes/0003355673) or [here](https://help.sap.com/docs/btp/sap-business-technology-platform/tips-and-tricks-for-node-js-applications?locale=en-US)  or try to reduce the memory from 256M to 128M in the `manifest.yml` file.

Best Regards
Padmapriya
